title = "#"
base_url = "/"
description = "a space in cyberspace."

generate_feeds = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

default_language = "en"

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[languages.se]
title = "#"
description = "En plats i cyberrymden."

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[languages.se.translations]
no_posts = "Ingen bloggpost"
remove_filter = "Ta bort filter"
filtering_for = "Filtrerar på"
made_with = "Skapat med"
table_of_contents = "Innehållsförteckning"
language = "Språk"
site = "sajt"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
date_format = "%Y-%m-%d"
webserver_sends_csp_headers = true
language_switcher = true
translations = [
  { code = "en", name = "English" },
  { code = "se", name = "Svenska" },
]

[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = true

[[extra.main_menu]]
name = "Home"
name_se = "Startsida"
url = "@/_index.md"

[[extra.main_menu]]
name = "Bear"
name_se = "Bear"
url = "@/bear.md"

[[extra.main_menu]]
name = "Zola"
name_se = "Zola"
url = "@/zola.md"

[[extra.main_menu]]
name = "Blog"
name_se = "Blog"
url = "@/blog/_index.md"
